- name: configure repo on all hosts
  hosts: all
  gather_facts: false
  become: true
  roles:
    - config-repo

- name: deploy haproxy
  hosts: frontends
  gather_facts: false
  become: true
  roles:
    - deploy-haproxy

- name: deploy tomcat
  hosts: apps
  gather_facts: false
  become: true
  roles:
    - deploy-tomcat

- name: index.html on app servers
  hosts: apps
  gather_facts: true
  become: true
  roles:
    - deploy-app

- name: deploy postgres
  gather_facts: false
  become: true
  hosts: appdbs
  roles:
    - deploy-db

