  - name: copy static index.html to app1 tomcat webapps/ansible/index.html
    template:
      src: index.html.app1
      dest: /usr/share/tomcat/webapps/ansible/index.html
    when: ansible_hostname == "app1"

  - name: copy static index.html to app2 tomcat webapps/ansible/index.html
    template:
      src: index.html.app2
      dest: /usr/share/tomcat/webapps/ansible/index.html
    when: ansible_hostname == "app2"
